"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const API_BASE_URL =
    process.env.NEXT_PUBLIC_BACKEND_URL;

export default function ChurchRegistrationPage() {
    const router = useRouter();

    const [churchName, setChurchName] = useState("");
    const [address, setAddress] = useState("");
    const [city, setCity] = useState("");
    const [state, setState] = useState("");
    const [country, setCountry] = useState("India");
    const [contactEmail, setContactEmail] = useState("");
    const [contactPhone, setContactPhone] = useState("");

    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        if (submitting) return;

        setError(null);

        const payload = {
            church_name: churchName.trim(),
            address: address.trim(),
            city: city.trim(),
            state: state.trim(),
            country: country.trim(),
            contact_email: contactEmail.trim().toLowerCase(),
            contact_phone: contactPhone.trim(),
        };

        if (!payload.church_name) {
            setError("Church name is required.");
            return;
        }

        if (!payload.city) {
            setError("City is required.");
            return;
        }

        if (!payload.state) {
            setError("State / Province is required.");
            return;
        }

        if (!payload.country) {
            setError("Country is required.");
            return;
        }

        if (
            payload.contact_email &&
            !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(
                payload.contact_email
            )
        ) {
            setError("Please enter a valid contact email address.");
            return;
        }

        setSubmitting(true);

        try {
            const response = await fetch(
                `${API_BASE_URL}/onboarding/register`,
                {
                    method: "POST",
                    headers: {
                        Accept: "application/json",
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(payload),
                }
            );

            const result = await response.json().catch(() => ({}));

            if (!response.ok) {
                if (response.status === 422) {
                    const validationMessage =
                        result?.message ||
                        Object.values(result?.errors || {})
                            .flat()
                            .map(String)
                            .join(" ");

                    throw new Error(
                        validationMessage ||
                        "Please correct the information and try again."
                    );
                }

                throw new Error(
                    result?.message ||
                    "Unable to register the church."
                );
            }





            const churchCode =
                result?.data?.church?.church_code;

            const church = result?.data?.church;

            if (!churchCode) {
                console.error("Unexpected registration response:", result);

                throw new Error(
                    "Church registration succeeded, but no Church Code was returned."
                );
            }

            // Store the registered church details
            localStorage.setItem(
                "platform_church",
                JSON.stringify(church)
            );

            // Store church code separately for easy access
            localStorage.setItem("church_code", churchCode);
            localStorage.setItem("church", church);

            console.log("Registered church stored:", church);

            if (!churchCode) {
                console.error("Unexpected registration response:", result);

                throw new Error(
                    "Church registration succeeded, but no Church Code was returned."
                );
            }

            /*
             * The Church Code is generated by Laravel.
             * The browser does not generate it.
             */
            router.push("/platform/setup-admin");
        } catch (error) {
            console.error(
                "Unable to register church:",
                error
            );

            setError(
                error instanceof Error
                    ? error.message
                    : "Unable to register the church."
            );

            setSubmitting(false);
        }
    };

    return (
        <main className="min-h-screen bg-slate-50">
            <div className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-6 lg:py-14">
                <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">

                    {/* Header */}
                    <div className="bg-[#191970] px-6 py-9 sm:px-10 sm:py-11">
                        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-amber-300">
                            Church Community
                        </p>

                        <h1 className="mt-3 text-2xl font-bold tracking-tight text-white sm:text-3xl">
                            Register your church
                        </h1>

                        <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-200">
                            Enter your church details to begin setting up
                            your Church Community account.
                        </p>
                    </div>

                    {/* Form */}
                    <form
                        onSubmit={handleSubmit}
                        className="space-y-6 px-6 py-8 sm:px-10 sm:py-10"
                    >
                        {/* Church information */}
                        <div>
                            <h2 className="text-base font-semibold text-slate-900">
                                Church Information
                            </h2>

                            <p className="mt-1 text-sm text-slate-500">
                                Please provide the official details of
                                your church.
                            </p>
                        </div>

                        {/* Church name */}
                        <div>
                            <label
                                htmlFor="church-name"
                                className="block text-sm font-medium text-slate-700"
                            >
                                Church Name
                                <span className="ml-1 text-red-500">
                                    *
                                </span>
                            </label>

                            <input
                                id="church-name"
                                type="text"
                                value={churchName}
                                onChange={(event) =>
                                    setChurchName(event.target.value)
                                }
                                disabled={submitting}
                                placeholder="Enter the official church name"
                                autoComplete="organization"
                                className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                            />
                        </div>

                        {/* Address */}
                        <div>
                            <label
                                htmlFor="church-address"
                                className="block text-sm font-medium text-slate-700"
                            >
                                Church Address
                            </label>

                            <textarea
                                id="church-address"
                                value={address}
                                onChange={(event) =>
                                    setAddress(event.target.value)
                                }
                                disabled={submitting}
                                placeholder="Enter the church address"
                                rows={3}
                                autoComplete="street-address"
                                className="mt-2 block w-full resize-none rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                            />
                        </div>

                        {/* Location */}
                        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                            <div>
                                <label
                                    htmlFor="church-city"
                                    className="block text-sm font-medium text-slate-700"
                                >
                                    City
                                    <span className="ml-1 text-red-500">
                                        *
                                    </span>
                                </label>

                                <input
                                    id="church-city"
                                    type="text"
                                    value={city}
                                    onChange={(event) =>
                                        setCity(event.target.value)
                                    }
                                    disabled={submitting}
                                    placeholder="City"
                                    autoComplete="address-level2"
                                    className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                                />
                            </div>

                            <div>
                                <label
                                    htmlFor="church-state"
                                    className="block text-sm font-medium text-slate-700"
                                >
                                    State / Province
                                    <span className="ml-1 text-red-500">
                                        *
                                    </span>
                                </label>

                                <input
                                    id="church-state"
                                    type="text"
                                    value={state}
                                    onChange={(event) =>
                                        setState(event.target.value)
                                    }
                                    disabled={submitting}
                                    placeholder="State / Province"
                                    autoComplete="address-level1"
                                    className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                                />
                            </div>
                        </div>

                        {/* Country */}
                        <div>
                            <label
                                htmlFor="church-country"
                                className="block text-sm font-medium text-slate-700"
                            >
                                Country
                                <span className="ml-1 text-red-500">
                                    *
                                </span>
                            </label>

                            <input
                                id="church-country"
                                type="text"
                                value={country}
                                onChange={(event) =>
                                    setCountry(event.target.value)
                                }
                                disabled={submitting}
                                placeholder="Country"
                                autoComplete="country-name"
                                className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                            />
                        </div>

                        {/* Contact */}
                        <div className="border-t border-slate-200 pt-6">
                            <h2 className="text-base font-semibold text-slate-900">
                                Church Contact Details
                            </h2>

                            <p className="mt-1 text-sm text-slate-500">
                                These details can be used for church
                                administration and communication.
                            </p>
                        </div>

                        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                            {/* Email */}
                            <div>
                                <label
                                    htmlFor="contact-email"
                                    className="block text-sm font-medium text-slate-700"
                                >
                                    Contact Email
                                </label>

                                <input
                                    id="contact-email"
                                    type="email"
                                    value={contactEmail}
                                    onChange={(event) =>
                                        setContactEmail(
                                            event.target.value
                                        )
                                    }
                                    disabled={submitting}
                                    placeholder="church@example.com"
                                    autoComplete="email"
                                    className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                                />
                            </div>

                            {/* Phone */}
                            <div>
                                <label
                                    htmlFor="contact-phone"
                                    className="block text-sm font-medium text-slate-700"
                                >
                                    Contact Phone
                                </label>

                                <input
                                    id="contact-phone"
                                    type="tel"
                                    value={contactPhone}
                                    onChange={(event) =>
                                        setContactPhone(
                                            event.target.value
                                        )
                                    }
                                    disabled={submitting}
                                    placeholder="Church contact number"
                                    autoComplete="tel"
                                    className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-2 focus:ring-slate-200 disabled:bg-slate-100"
                                />
                            </div>
                        </div>

                        {/* Error */}
                        {error && (
                            <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
                                <p className="text-sm font-medium leading-5 text-red-700">
                                    {error}
                                </p>
                            </div>
                        )}

                        {/* Information */}
                        <div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-4">
                            <p className="text-sm leading-6 text-blue-800">
                                After registration, your church will receive
                                a unique Church Code. You will then create
                                the Setup Administrator account for your
                                church.
                            </p>
                        </div>

                        {/* Actions */}
                        <div className="flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:items-center sm:justify-between">
                            <button
                                type="button"
                                onClick={() =>
                                    router.push(
                                        "/platform/getting-started"
                                    )
                                }
                                disabled={submitting}
                                className="inline-flex items-center justify-center rounded-lg border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
                            >
                                Back
                            </button>

                            <button
                                type="submit"
                                disabled={submitting}
                                className="inline-flex items-center justify-center rounded-lg bg-[#191970] px-6 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[#15155f] focus:outline-none focus:ring-2 focus:ring-[#191970] focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60"
                            >
                                {submitting
                                    ? "Registering Church..."
                                    : "Register Church"}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </main>
    );
}