import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "../components/sidebar";
import { AuthProvider } from "../context/auth-provider";







const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <div className="w-full flex bg-[#272757]">
                {/* Sidebar */}
                <div className="fixed left-0 top-0 w-[15%] min-h-screen bg-[#272757]">
                    <Sidebar />
                </div>

                {/* Content */}
                <div className="ml-[15%] w-[85%] bg-blue-50 mt-30 min-h-screen">
                    <div className="w-full px-1">
                        {children}
                    </div>
                </div>
            </div>
        </AuthProvider>
    );
}
